use_frameworks!

platform :ios, '8.0'
source 'https://cdn.cocoapods.org/'
source 'https://github.com/wuzhengchuang/BeautySpec.git'
target 'BeautyMineMoudle_Example' do
  pod 'BeautyMineMoudle', :path => '../'

  target 'BeautyMineMoudle_Tests' do
    inherit! :search_paths

    
  end
end
